export enum SectionType {
  PERSONAL_INFO = 'PERSONAL_INFO',
  EDUCATION = 'EDUCATION',
  EXPERIENCE = 'EXPERIENCE',
  SKILLS = 'SKILLS',
  PROJECTS = 'PROJECTS',
  CERTIFICATIONS = 'CERTIFICATIONS',
  OTHER = 'OTHER'
}

